### PR TITLE
New Features

### PR DESCRIPTION
**Pull request by jvukovich**
Howdy,

We ran through a thorough test of Bounce and integrated it with our project. We discovered some features that would be really useful for us, so we integrated them and created this pull request.

Please let us know if you think these could be done better, or if there were ways to handle this without making modifications, etc.

Thanks!
Jon Vukovich (NBucket)
jon.vukovich@gmail.com

### CODE REVIEW

**Comment by refractalize** [comment]
Hi, I'm not particularly sure about the first commit for multiple task execution. This kind of breaks the whole `bounce task /arg1:value1`. If you have multiple tasks, how do you pass arguments, and which arguments go to which tasks?

Otherwise the rest of the commits look fine. Can you write some tests? See [RunningTasksTests](https://github.com/refractalize/bounce/blob/master/Bounce.Console.Tests/RunningTasksTests.cs).

**Comment by refractalize** [comment]
I've pushed my merged version of your repo into the [nbucket](https://github.com/refractalize/bounce/tree/nbucket) branch, for reference.

**Comment by jvukovich** [comment]
Cool, thanks Tim!

I got around the parameter issue by adding a static dictionary and putting all param/values into it (commit 4cba585). So, in our build scripts, we can access them from anywhere/any task, rather than as method parameters: var param1 = Props.Get("param1");

Couldn't think of a better way to handle it.

I'll get some tests together as soon as I have some free time.

Thanks again!

**Comment by refractalize** [comment]
I think the problem was that when I ran something like `bounce task1 /arg1 value1` it was trying to run a two tasks `task1` and `value1`, thinking that `value1` was a task name not a parameter value. Think you need to stop parsing tasks as soon as you see an `/arg`. I.e. `bounce task1 task2 /arg1 value1` just takes the task names up until the first `/arg1`.

**Comment by jvukovich** [comment]
Ah okay, thanks!

Ah ha, I misread the docs (https://github.com/refractalize/bounce). At the bottom, where is notates passing arg/values; I thought they were separated by a colon. But, it's actually an equal sign (MyProject.Bounce.Stuff.Hello /name:string = all).

So, it should also support passing arg values without a '=' delimiter, as you stated? (/arg1 value1)

Just checking before proceeding with changes/tests. Thanks!

**Comment by refractalize** [comment]
hi @jvukovich, just need to support `/arg:value` and `/arg value`. cheers!

**Comment by jvukovich** [comment]
Updated pull request (commit 26f091d).

**Comment by jvukovich** [comment]
Any issues with my pull request? Haven't heard from you, so thought I would ping again. Happy Holidays! Thanks!

**Comment by jvukovich** [comment]
Hey man, just checking in again. Do you need any help from me on getting this merged? Thanks!

**Comment by jvukovich** [comment]
Checking in again. Do you need anything from me to get this merged?

**Comment by jvukovich** [comment]
Checking in again. Do you need anything from me to get this merged? Approaching a year since my pull request.

**Comment by jvukovich** [comment]
Conflicts addressed. Upgraded Bounce to .NET 4.6.1. Changed the MsBuild path discovery to use the Windows registry, as it appears Microsoft.Build.Utilities is outdated.

**Comment by jvukovich** [comment]
Merge fixes and made BadExitException serializable.

**Pull request merged**
